name: Continuous Integration

on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  shellcheck:
    if: github.event_name != 'pull_request' || (github.event_name == 'pull_request' && github.event.pull_request.draft == false)
    name: Shellcheck
    uses: ./.github/workflows/shellcheck.yml
