name: Continuous Integration

on:
  push:
    branches: [dev]
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version

      - name: Install dependencies
        run: npm ci

      - name: Prebuild (clean dist folder)
        run: npm run prebuild

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Run tests with coverage
        run: npm run test:cov
